# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: How To Use SURROGATE
email: contact@hasdesk.com
description: >- # this means to ignore newlines until "baseurl:"
  This documentaion is WIP and constantly been updated with how to use the newest features on Surrogate.
baseurl: "/surrogatefaq/" # the subpath of your site, e.g. /blog
url: "https://teejavus.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hereafterhub
#github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed


  